spring:
  profiles:
    default: prod
  application:
    name: did-it-backend
  datasource:
    url: jdbc:postgresql://121.170.121.187:5432/postgres
    username: postgres
    password: 1234
  sql:
    init:
      platform: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  secret: 031eaa8bbd06df8c52dfb861adc301d27eaf44fb941101feb52b83a59f9b2f73

server:
  port: 8080